### ISSUE TITLE
OasisScan Escrow Table Pagination Issue

### ISSUE THREAD

**Issue by atharen** [bitcat365/oasisscan-frontend#6] opened 2022-11-15 11:26 UTC
Using [BinanceStaking Validator Page](https://www.oasisscan.com/validators/detail/oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm) as an example:

Clicking to go to the last page of the paginated view for the **Escrow Event** table (Picture 1), breaks the element, resulting in 'No Escrow Event' being displayed (Picture 2).

1. 
![OasisScan Validator Page - 1](https://user-images.githubusercontent.com/23165475/201907672-d598b42e-b0c9-47e5-9f87-6e0ed6cc9111.png)

2. 
![OasisScan Validator Page - 2](https://user-images.githubusercontent.com/23165475/201907677-79cf0c05-5809-496e-a7bd-4874f186ab51.png)

**Comment by atharen** [comment] 2022-11-15 11:31
I looked at the network requests, and there was a GET request to the following endpoint, which returned no data:
https://www.oasisscan.com/mainnet/chain/powerevent?address=oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm&page=9270&size=5

_Tried page 9269 manually and also encountered the same back-end issue..._

**Comment by romever** [comment] 2022-11-15 13:40
This bug is caused by the fact that the details of early transactions cannot be queried on the current network.It is now fixed to only show the transaction starting from the initial height of the current network.
Thanks for feedback.

**Closed** 2023-11-29 14:49 UTC
